name: extract-version

on:
  workflow_call:
    inputs:
      git-tag-ref:
        type: string
        description: git-tag-ref
        required: true  
    secrets:
      GH_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
     value: ${{ steps.version.outputs.value }}
    steps:
      - name: Clone Repository
        if: inputs.git-tag-ref == 'latest' || inputs.git-tag-ref == 'previous'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set latest version
        if: inputs.git-tag-ref == 'latest'
        run: echo "VERSION=`echo $(git describe --tags $(git rev-list --tags --max-count=1))`" >> $GITHUB_ENV

      - name: Set previous version
        if: inputs.git-tag-ref == 'previous'
        run: echo "VERSION=`echo $(git describe --always --abbrev=0 --tags $(git describe --tags $(git rev-list --tags --max-count=1))^)`" >> $GITHUB_ENV

      - name: Set custom version
        if: inputs.git-tag-ref != 'latest' && inputs.git-tag-ref != 'previous'
        run: echo "VERSION=`echo ${{ github.event.client_payload.git-tag-ref }}`" >> $GITHUB_ENV
     
      - id: version 
        run: echo "::set-output name=value::${{env.VERSION}}"
