name: scala-publish

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout / Setup JDK 8 / SBT-Cache
        uses: rodobarcaaa/action-jdk-sbt-cache@v1.0.0
        with:
          token: ${{ env.GITHUB_TOKEN }}
          jdk-version: '11'
          fetch-depth: '0'

      - run: SBT_OPTS="-Xms1024M -Xmx2560M -Xss2M -XX:+UseG1GC" sbt publish
 
