name: scala-ci

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  coventional:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  labeler:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - name: Label the PR action
        uses: TimonVS/pr-labeler-action@v4
        with:
          configuration-path: .github/labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  check:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    timeout-minutes: 30
    steps:
      - name: Checkout / Setup JDK / SBT-Cache
        uses: Travelonux/action-jdk-sbt-cache.yml@main
        with:
          token: ${{ env.GITHUB_TOKEN }}
          jdk-version: '11'

      - run: SBT_OPTS="-Xms1024M -Xmx2560M -Xss2M -XX:+UseG1GC" sbt build

      - run: SBT_OPTS="-Xms1024M -Xmx2560M -Xss2M -XX:+UseG1GC" sbt unitTests

  merge:
    if: startsWith(github.event.pull_request.head.ref, 'update') && github.actor == 'travelonux-dev'
    needs: [check]
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: desbo/merge-pr-action@v0
        continue-on-error: true
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          ALLOWED_UPDATE: minor
          MERGE_METHOD: squash
