name: scala-publish

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout / Setup JDK 8 / SBT-Cache
        uses: Travelonux/action-jdk-sbt-cache@main
        with:
          token: ${{ env.GITHUB_TOKEN }}
          jdk-version: '8'
          fetch-depth: '0'

      - run: SBT_OPTS="-Xms2048M -Xmx4096M -Xss2M -XX:+UseG1GC" sbt publish
 
