name: scala-formatter

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  formatter:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}    
    steps:
      - name: Checkout / Setup JDK 8 / SBT-Cache
        uses: rodobarcaaa/action-jdk-sbt-cache@v1.0.0
        with:
          token: ${{ env.GITHUB_TOKEN }}
          jdk-version: '8'
          fetch-depth: '0'

      - name: Scala FMT
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          SBT_OPTS="-Xms1024M -Xmx2560M -Xss2M -XX:+UseG1GC" sbt scalafmtAll
          git add -A
          git commit -m "chore: formating code with scalafmt [actions skip]"
          git push
